version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: providers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/providers
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    volumes:
      - ./MUP_INP_RY24_P03_V10_DY22_PrvSvc.csv:/app/MUP_INP_RY24_P03_V10_DY22_PrvSvc.csv
      - ./USZipsWithLatLon_20231227.csv:/app/USZipsWithLatLon_20231227.csv

volumes:
  postgres_data: 